from __future__ import annotations
from argparse import ArgumentParser, _SubParsersAction
from pathlib import Path
import logging
from typing import List
from . import register
from ..errors import EidonError

logger = logging.getLogger("eidon.init")

_TEMPLATE_GITIGNORE = """__pycache__/
*.pyc
.env
.venv/
dist/
build/
"""

_TEMPLATE_README = """# New Eidon project

Generated by `eidon init`.
"""

_TEMPLATE_EIDON_TOML = '''# Eidon project configuration
default_name = "World"

[logging]
level = "INFO"
'''


def _write_file(path: Path, content: str, overwrite: bool, created: List[str], overwritten: List[str]) -> None:
    if path.exists():
        if overwrite:
            path.write_text(content, encoding="utf-8")
            overwritten.append(str(path))
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        created.append(str(path))


def _run(args) -> int:
    target = Path(args.path).expanduser().resolve()
    force = bool(getattr(args, "force", False))
    fmt = getattr(args, "format", "text")

    # Safety checks
    if target.exists():
        if target.is_dir():
            if any(target.iterdir()) and not force:
                raise EidonError(f"Target '{target}' exists and is not empty; use --force to overwrite.", code=4)
        else:
            raise EidonError(f"Target '{target}' exists and is a file; choose a directory path.", code=4)
    else:
        target.mkdir(parents=True, exist_ok=True)

    created: List[str] = []
    overwritten: List[str] = []

    # Write core files (overwrite these if --force)
    _write_file(target / ".gitignore", _TEMPLATE_GITIGNORE, force, created, overwritten)
    _write_file(target / "README.md", _TEMPLATE_README, force, created, overwritten)
    _write_file(target / "eidon.toml", _TEMPLATE_EIDON_TOML, force, created, overwritten)

    # Create a couple of helpful folders
    for d in ["data", "docs"]:
        p = target / d
        if not p.exists():
            p.mkdir(parents=True, exist_ok=True)
            created.append(str(p))

    logger.info("Scaffold created at %s", target)

    if fmt == "json":
        import json
        payload = {
            "ok": True,
            "command": "init",
            "path": str(target),
            "created": created,
            "overwritten": overwritten,
        }
        print(json.dumps(payload, ensure_ascii=False, separators=(",", ":")))
    else:
        print(f"Initialized Eidon scaffold at {target}.")
        if created:
            print("Created:")
            for c in created:
                print(f"  {c}")
        if overwritten:
            print("Overwritten:")
            for c in overwritten:
                print(f"  {c}")
    return 0


@register
def register_init(subparsers: _SubParsersAction) -> None:
    p: ArgumentParser = subparsers.add_parser(
        "init",
        help="Create a minimal Eidon project scaffold at the given path.",
        description="Scaffold folders and config for a new Eidon project.",
    )
    p.add_argument("path", help="Target directory to create or reuse.")
    p.add_argument("--force", action="store_true", help="Overwrite existing files if the target directory is not empty.")
    p.add_argument("--format", choices=["text", "json"], default="text")
    p.set_defaults(func=_run)
